# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewVer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_ver(object):
    def setupUi(self, new_ver):
        new_ver.setObjectName("new_ver")
        new_ver.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(new_ver.sizePolicy().hasHeightForWidth())
        new_ver.setSizePolicy(sizePolicy)
        new_ver.setMinimumSize(QtCore.QSize(500, 300))
        new_ver.setMaximumSize(QtCore.QSize(500, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(new_ver)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_version_label = QtWidgets.QLabel(new_ver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_version_label.sizePolicy().hasHeightForWidth())
        self.new_version_label.setSizePolicy(sizePolicy)
        self.new_version_label.setObjectName("new_version_label")
        self.horizontalLayout_2.addWidget(self.new_version_label)
        self.new_version = QtWidgets.QLabel(new_ver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_version.sizePolicy().hasHeightForWidth())
        self.new_version.setSizePolicy(sizePolicy)
        self.new_version.setObjectName("new_version")
        self.horizontalLayout_2.addWidget(self.new_version)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.update_body_textBrowser = QtWidgets.QTextBrowser(new_ver)
        self.update_body_textBrowser.setObjectName("update_body_textBrowser")
        self.verticalLayout_3.addWidget(self.update_body_textBrowser)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.never_remind_me_checkBox = QtWidgets.QCheckBox(new_ver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.never_remind_me_checkBox.sizePolicy().hasHeightForWidth())
        self.never_remind_me_checkBox.setSizePolicy(sizePolicy)
        self.never_remind_me_checkBox.setObjectName("never_remind_me_checkBox")
        self.horizontalLayout.addWidget(self.never_remind_me_checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.remind_me_next_time_pushButton = QtWidgets.QPushButton(new_ver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remind_me_next_time_pushButton.sizePolicy().hasHeightForWidth())
        self.remind_me_next_time_pushButton.setSizePolicy(sizePolicy)
        self.remind_me_next_time_pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.remind_me_next_time_pushButton.setObjectName("remind_me_next_time_pushButton")
        self.horizontalLayout.addWidget(self.remind_me_next_time_pushButton)
        self.download_pushButton = QtWidgets.QPushButton(new_ver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_pushButton.sizePolicy().hasHeightForWidth())
        self.download_pushButton.setSizePolicy(sizePolicy)
        self.download_pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.download_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.download_pushButton.setObjectName("download_pushButton")
        self.horizontalLayout.addWidget(self.download_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(new_ver)
        QtCore.QMetaObject.connectSlotsByName(new_ver)

    def retranslateUi(self, new_ver):
        _translate = QtCore.QCoreApplication.translate
        new_ver.setWindowTitle(_translate("new_ver", "DIscord狀態修改器 新版本通知"))
        self.new_version_label.setText(_translate("new_ver", "檢測到新版本: "))
        self.new_version.setText(_translate("new_ver", "0.0.0"))
        self.never_remind_me_checkBox.setText(_translate("new_ver", "不要再提醒我"))
        self.remind_me_next_time_pushButton.setText(_translate("new_ver", "下次提醒我"))
        self.download_pushButton.setText(_translate("new_ver", "前往下載"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_ver = QtWidgets.QWidget()
    ui = Ui_new_ver()
    ui.setupUi(new_ver)
    new_ver.show()
    sys.exit(app.exec_())
